{ pkgs, ... }:
{
  home.packages = [
    pkgs.matugen

    (pkgs.writeShellScriptBin "wallpaper-theme" ''
      set -euo pipefail
      IMG="''${1:-$HOME/.config/wallpaper}"
      MODE="''${2:-dark}"

      if [ ! -e "$IMG" ]; then
        echo "No image at: $IMG"
        echo "Usage: wallpaper-theme [/path/to/image] [dark|light]"
        exit 1
      fi

      mkdir -p "$HOME/.config/nixos-theme"
      ${pkgs.matugen}/bin/matugen image "$IMG" -m "$MODE" \
        --config "$HOME/.config/matugen/config.toml"

      echo ""
      echo "Generated: $HOME/.config/nixos-theme/generated-theme.nix"
      echo "Set 'theme = themes.generated;' at the bottom of home/theme.nix, then rebuild."
    '')
  ];

  xdg.configFile."matugen/config.toml".text = ''
    [config]

    [templates.nixtheme]
    input_path = "~/.config/matugen/templates/nixtheme.nix.template"
    output_path = "~/.config/nixos-theme/generated-theme.nix"
  '';

  xdg.configFile."matugen/templates/nixtheme.nix.template".text = ''
    # Auto-generated by matugen — do not edit by hand.
    # Regenerate with: wallpaper-theme /path/to/wallpaper.jpg
    {
      bg = "{{colors.background.dark.hex}}";
      surface = "{{colors.surface_variant.dark.hex}}";
      fg = "{{colors.on_background.dark.hex}}";
      accent = "{{colors.primary.dark.hex}}";
      hover = "{{colors.secondary_container.dark.hex}}";
      red = "{{colors.error.dark.hex}}";
      green = "{{colors.secondary.dark.hex}}";
      yellow = "{{colors.tertiary.dark.hex}}";
      contrast = "{{colors.on_primary.dark.hex}}";
      shadow = "{{colors.shadow.dark.hex}}";
      dim = "0.35";
      calMonth = "{{colors.on_background.dark.hex}}";
      calWeekdays = "{{colors.tertiary.dark.hex}}";
      calToday = "{{colors.primary.dark.hex}}";

      hypr = {
        active_border = "rgba({{colors.primary.dark.hex_stripped}}ff)";
        inactive_border = "rgba({{colors.outline_variant.dark.hex_stripped}}aa)";
        shadow = "rgba(00000077)";
      };

      term = {
        bg = "{{colors.background.dark.hex}}";
        fg = "{{colors.on_background.dark.hex}}";
        selText = "{{colors.on_secondary_container.dark.hex}}";
        selBg = "{{colors.secondary_container.dark.hex}}";
        curText = "{{colors.background.dark.hex}}";
        curCursor = "{{colors.primary.dark.hex}}";
        black = "{{colors.background.dark.hex}}";
        red = "{{colors.error.dark.hex}}";
        green = "{{colors.secondary.dark.hex}}";
        yellow = "{{colors.tertiary.dark.hex}}";
        blue = "{{colors.primary.dark.hex}}";
        magenta = "{{colors.tertiary_container.dark.hex}}";
        cyan = "{{colors.secondary_container.dark.hex}}";
        white = "{{colors.on_background.dark.hex}}";
        brBlack = "{{colors.outline.dark.hex}}";
        brRed = "{{colors.on_error_container.dark.hex}}";
        brGreen = "{{colors.on_secondary_container.dark.hex}}";
        brYellow = "{{colors.on_tertiary_container.dark.hex}}";
        brBlue = "{{colors.on_primary_container.dark.hex}}";
        brMagenta = "{{colors.tertiary.dark.hex}}";
        brCyan = "{{colors.secondary.dark.hex}}";
        brWhite = "{{colors.on_surface.dark.hex}}";
      };

      fuzzel = {
        bg = "{{colors.background.dark.hex_stripped}}ee";
        text = "{{colors.on_background.dark.hex_stripped}}ff";
        match = "{{colors.primary.dark.hex_stripped}}ff";
        selection = "{{colors.secondary_container.dark.hex_stripped}}ff";
        selText = "{{colors.on_secondary_container.dark.hex_stripped}}ff";
        selMatch = "{{colors.primary.dark.hex_stripped}}ff";
        border = "{{colors.primary.dark.hex_stripped}}ff";
      };
    }
  '';
}
